export KEYCLOAK_DATABASE_PASSWORD="koira"  # pragma: allowlist secret
export RM_DATABASE_PASSWORD="kissa"  # pragma: allowlist secret
export POSTGRES_PASSWORD="kani"  # pragma: allowlist secret
export LDAP_ADMIN_PASSWORD="pupu"  # pragma: allowlist secret
export KEYCLOAK_ADMIN_PASSWORD="marsu"  # pragma: allowlist secret
export KEYCLOAK_MANAGEMENT_PASSWORD="alpakka"  # pragma: allowlist secret
export TAK_DATABASE_PASSWORD="laama"  # pragma: allowlist secret
export SERVER_DOMAIN="localmaeher.pvarki.fi"
export CFSSL_CA_NAME="localmaeher"
export MW_LE_EMAIL="example@example.com"
export MW_LE_TEST="true"  # switch to false when you are ready for production
export TAKSERVER_CERT_PASS="KissaKoira123!AlpakkaMursu"  # used for the JKS
export TAK_CA_PASS="AlpakkaMursu!KissaKoira123"  # used for the JKS
export KIBANA_DOMAIN="kibana.${SERVER_DOMAIN}" # Set kibana domain, if you want to use kibana locally
export VITE_ASSET_SET="${VITE_ASSET_SET:-neutral}"  # used RMUI to define asset sets (logos, etc).
export ELASTIC_AGENT_ENABLED="false" # If you want to enable ElasticAgent for fleet configuration, set true
export ELASTIC_AGENT_ENROLLMENT_TOKEN= # Token for Elastic fleet enrolment
export ELASTIC_AGENT_FLEET_URL= #Url for Elasti fleet enrolment
export LOG_INPUT_ENABLED="true"
