export KEYCLOAK_DATABASE_PASSWORD="koira"  # pragma: allowlist secret
export RM_DATABASE_PASSWORD="kissa"  # pragma: allowlist secret
export POSTGRES_PASSWORD="kani"  # pragma: allowlist secret
export LDAP_ADMIN_PASSWORD="pupu"  # pragma: allowlist secret
export KEYCLOAK_ADMIN_PASSWORD="marsu"  # pragma: allowlist secret
export TAK_DATABASE_PASSWORD="laama"  # pragma: allowlist secret
export SYNAPSE_DATABASE_PASSWORD="mammutti"  # pragma: allowlist secret
export SYNAPSE_MACAROON_SECRET_KEY="krokotiili" # pragma: allowlist secret
export MAS_DATABASE_PASSWORD="vompatti"  # pragma: allowlist secret
export MAS_ENCRYPTION_SECRET="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"  # openssl rand -hex 32 # pragma: allowlist secret
export MAS_SYNAPSE_SECRET="saukko"  # pragma: allowlist secret
export MAS_ADMIN_CLIENT_SECRET="liikeri"  # pragma: allowlist secret
export SERVER_DOMAIN="localmaeher.dev.pvarki.fi"
export CFSSL_CA_NAME="localmaeher"
export MW_LE_EMAIL="example@example.com"
export MW_LE_TEST="true"  # switch to false when you are ready for production
export TAKSERVER_CERT_PASS="KissaKoira123!AlpakkaMursu"  # used for the JKS
export TAK_CA_PASS="AlpakkaMursu!KissaKoira123"  # used for the JKS
export VITE_THEME="${VITE_THEME:-default}"  # used RMUI to define asset sets (logos, etc).
export KEYCLOAK_PROFILEROOT_UUID="4f88fe8c-ffa5-4ae4-97c9-3831a500d502"  # use uuidgen -r in production
export KEYCLOAK_HTTPS_KEY_STORE_PASSWORD="chinchilla"  # pragma: allowlist secret
export KEYCLOAK_HTTPS_TRUST_STORE_PASSWORD="iguaani"  # pragma: allowlist secret
export BL_DATABASE_PASSWORD="rotta"  # pragma: allowlist secret
export RMMTX_DATABASE_PASSWORD="capybara"  # pragma: allowlist secret
export RMMTX_API_PASSWORD="myyra"  # pragma: allowlist secret
export RMMTX_SRT_PUB_PASSWORD="mesimayra"  # pragma: allowlist secret
export RMMTX_SRT_READ_PASSWORD="gerbiili"  # pragma: allowlist secret
