sequenceDiagram
    hallintakännykkä->>toinen kännykkä: anna <invite_code> tai näytä QR
    toinen kännykkä->>API: /enrollment/invitecode?code=<invite_code>
    API->>toinen kännykkä: <invite_code active: true/false>
    toinen kännykkä->>toinen kännykkä: onko <invite_code> ok?
    toinen kännykkä->>API: /enrollment/invitecode/enroll: {<invite_code>, <work_id>}
    API->>toinen kännykkä: <user_jwt>
    toinen kännykkä->>API: /enrollment/have-I-been-accepted
    API->>toinen kännykkä: <false>
    toinen kännykkä->>toinen kännykkä: onko minut hyväksytty?
    hallintakännykkä->>API: /enrollment/list
    API->>hallintakännykkä: <users_list>
    hallintakännykkä->>hallintakännykkä: toinen kännykkä näkyy
    hallintakännykkä->>API: /enrollment/accept: {<work_id>}
    API->>hallintakännykkä: <OK>
    toinen kännykkä->>API: /enrollment/have-I-been-accepted
    API->>toinen kännykkä: <true>
    toinen kännykkä->>toinen kännykkä: minut on hyväksytty
    toinen kännykkä->>toinen kännykkä: hae MTLS certifikaatti.zip
    toinen kännykkä->>API: /enduserpfx/callsign
    API->>toinen kännykkä: <MTLS cert bundle>
    toinen kännykkä->>toinen kännykkä: onko MTLS cerfikaatti.zip ok?
