# renew_before_expiry = 30 days
version = 2.11.1
archive_dir = /data/persistent/le/conf/archive/rasenmaeher
cert = /data/persistent/le/conf/live/rasenmaeher/cert.pem
privkey = /data/persistent/le/conf/live/rasenmaeher/privkey.pem
chain = /data/persistent/le/conf/live/rasenmaeher/chain.pem
fullchain = /data/persistent/le/conf/live/rasenmaeher/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 6ff43ef59031cee28a4e488e1bd96549
key_type = rsa
config_dir = /data/persistent/le/conf
work_dir = /data/persistent/le/work
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
