name: Sphinx docs to gh-pages

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:  # Allow manual triggering

jobs:
  sphinx_docs_to_gh-pages:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Doxy
        run: sudo apt-get update -y && sudo apt-get install doxygen -y
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r docs/requirements.txt
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html
          destination_dir: docs
          publish_branch: gh-pages
